language: cpp
matrix:
    include:
        - os: linux
          env: WANT_KDE=NO
          compiler: gcc
        - os: linux
          env: WANT_KDE=YES
          compiler: gcc
        - os: osx
          compiler: clang
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cat /proc/cpuinfo /proc/meminfo; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then lsb_release -a; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sw_vers; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sysctl -a | grep cpu; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sysctl -a | grep mem; fi
    - pwd
install:
    - CMAKE_ARGS=""
    - |
        if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
          # want cmake newer than in ubuntu 12.04
          sudo add-apt-repository -y ppa:yjwong/cmake
          sudo apt-get update
          sudo apt-get install cmake cmake-data

          sudo apt-get install libperl-dev libenchant-dev

          CMAKE_ARGS="$CMAKE_ARGS -DWANT_KDE=$WANT_KDE"
          if [[ "$WANT_KDE" == "YES" ]]; then
            sudo apt-get install kdelibs5-dev
          fi
        fi
    - |
        if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          brew update
          brew install qt enchant
        fi
script:
    - mkdir build
    - cd build
    - cmake $CMAKE_ARGS ..
    - make -j3
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo make install; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make install; fi
    - ls -l
# TODO: build .dmg on osx and upload it
