language: cpp
os:
    - linux
compiler:
    - gcc
install:
    - cat /proc/cpuinfo /proc/meminfo
    - lsb_release -a
      # want cmake newer than in ubuntu 12.04
    - sudo add-apt-repository -y ppa:sschuberth/cmake-here
    - sudo apt-get update
    - sudo apt-get install libperl-dev cmake cmake-data
script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j3
    - sudo make install
