language: cpp
os:
    - linux
    - osx
compiler:
    - gcc
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cat /proc/cpuinfo /proc/meminfo; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then lsb_release -a; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sw_vers; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sysctl -a | grep cpu; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sysctl -a | grep mem; fi
    - pwd
install:
    - |
        if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
          # want cmake newer than in ubuntu 12.04
          sudo add-apt-repository -y ppa:sschuberth/cmake-here
          sudo apt-get update
          sudo apt-get install libperl-dev cmake cmake-data
        fi
    - |
        if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          brew update
          brew install qt enchant
        fi
script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j3
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo make install; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make install; fi
    - ls -l
